name: Run Tests

on:
  push:
    branches:
      - dev
      - main
      - release/*
  pull_request:
    branches:
      - dev
      - main

jobs:
  core:
    name: Build & Test Solution
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 📦 Install dependencies
        run: dotnet restore

      - name: 🛠 Build solution
        run: dotnet build --no-restore --configuration Release

      - name: 🧪 Run tests with coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: 🛠 Build release for x64
        run: dotnet build --no-restore --configuration Release -p:Platform=x64 -p:OutputPath=artifacts/x64

      - name: 🛠 Build release for x86
        run: dotnet build --no-restore --configuration Release -p:Platform=x86 -p:OutputPath=artifacts/x86

      - name: 📤 Upload x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: DQXLauncher.Toolbox-x64.exe
          path: artifacts/x64/DQXLauncher.Toolbox.exe

      - name: 📤 Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: DQXLauncher.Toolbox-x86.exe
          path: artifacts/x86/DQXLauncher.Toolbox.exe
